### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ehsaneha** [nicknochnack/TensorflowKeras-ReinforcementLearning#1]
I'm getting this error when trying to use your code can u help me please?
```
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    dqn.compile(Adam(lr=1e-3), metrics=['mae'])
  File "C:\Users\ehsan\AppData\Local\Programs\Python\Python38\lib\site-packages\rl\agents\dqn.py", line 168, in compile
    self.target_model = clone_model(self.model, self.custom_model_objects)
  File "C:\Users\ehsan\AppData\Local\Programs\Python\Python38\lib\site-packages\rl\util.py", line 16, in clone_model
    clone.set_weights(model.get_weights())
  File "C:\Users\ehsan\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 181, in get_weights
    self._compile_time_distribution_strategy)
AttributeError: 'Sequential' object has no attribute '_compile_time_distribution_strategy'
```

**Comment by nicknochnack** [comment]
Heya @ehsaneha, can you try deleting the model (code: del model) and then rerun the cells again?

**Comment by MarcusFutterlieb** [comment]
> 
> 
> Heya @ehsaneha, can you try deleting the model (code: del model) and then rerun the cells again?

Hey there, i am having the same issue and deleting the model was not successful. Any other ideas?

Kind regards
Marcus

**Comment by SachinDas246** [comment]
Its some kind of  tensorflow keras import issue ,try this code it worked for me, use this till training the agent (while using the code for saving and reloading weights don't forget to update some variable names ).



```
#1.import libraries
import numpy as np
import gym
​
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from keras.optimizers import Adam
​
from rl.agents.dqn import DQNAgent
from rl.policy import BoltzmannQPolicy
from rl.memory import SequentialMemory

#Get the environment and extract the number of actions
ENV_NAME = 'CartPole-v0'
env = gym.make(ENV_NAME)
np.random.seed(123)
env.seed(123)
actions = env.action_space.n
states = env.observation_space.shape

#2.Build Model:
def build_model(states, actions):    
    model = Sequential()
    model.add(Flatten(input_shape=(1,) + states ))
    model.add(Dense(16))
    model.add(Activation('relu'))
    model.add(Dense(16))
    model.add(Activation('relu'))
    model.add(Dense(16))
    model.add(Activation('relu'))
    model.add(Dense(nb_actions))
    model.add(Activation('linear'))    
    return model

model = build_model(states, actions)
model.summary()

#3.Build Agent with Keras-RL

def build_agent(model, actions):
    policy = BoltzmannQPolicy()
    memory = SequentialMemory(limit=50000, window_length=1)
    dqn = DQNAgent(model=model, nb_actions=actions, memory=memory, nb_steps_warmup=10,target_model_update=1e-2, policy=policy)
    return dqn

dqn = build_agent(model, actions)
dqn.compile(Adam(lr=1e-3), metrics=['mae'])
dqn.fit(env, nb_steps=100, visualize=True, verbose=2)

scores = dqn.test(env, nb_episodes=50000, visualize=False)
print(np.mean(scores.history['episode_reward']))

_ = dqn.test(env, nb_episodes=15, visualize=True)




```

**Comment by Suraj983-web** [comment]
------------------------------------------------------------------
AttributeError                   Traceback (most recent call last)
<ipython-input-11-5752e3d6b930> in <module>
      1 dqn = build_agent(model, actions)
----> 2 dqn.compile(Adam(lr=1e-3), metrics=['mae'])
      3 dqn.fit(env, nb_steps=100, visualize=True, verbose=2)

c:\users\chauhan-pc\appdata\local\programs\python\python38\lib\site-packages\rl\agents\dqn.py in compile(self, optimizer, metrics)
    166 
    167         # We never train the target model, hence we can set the optimizer and loss arbitrarily.
--> 168         self.target_model = clone_model(self.model, self.custom_model_objects)
    169         self.target_model.compile(optimizer='sgd', loss='mse')
    170         self.model.compile(optimizer='sgd', loss='mse')

c:\users\chauhan-pc\appdata\local\programs\python\python38\lib\site-packages\rl\util.py in clone_model(model, custom_objects)
     14     }
     15     clone = model_from_config(config, custom_objects=custom_objects)
---> 16     clone.set_weights(model.get_weights())
     17     return clone
     18 

c:\users\chauhan-pc\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\keras\engine\training_v1.py in get_weights(self)
    177     """
    178     strategy = (self._distribution_strategy or
--> 179                 self._compile_time_distribution_strategy)
    180     if strategy:
    181       with strategy.scope():

AttributeError: 'Sequential' object has no attribute '_compile_time_distribution_strategy'

**Comment by rjoseph24** [comment]
To solve that AttributeError: 'Sequential'.... just before you call the function for building the agent (build_agent) insert these 2 lines:

del model
model = build_model(states, actions)

Basically delete the model and create another model object by calling the function build_model.

After this, you will be able to run the dqn bit for building agent and compiling.

Found this after going through some Youtube comments.

**Comment by kanakmi** [comment]
@nicknochnack sir I have been able to resolve all these errors and have made a Jupyter Notebook similar to yours which everyone can follow. If I open a PR for the same, would you allow it to merge?
